<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS004-Cart</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5d4a1aec-4f08-4f08-a26f-1c6e90ced0d2</testSuiteGuid>
   <testCaseLink>
      <guid>c267bc8c-2e01-451d-bbda-7422ff73322f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/User ingin melakukan checkout produk tanpa mengisi credentials first name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d0d5ee5-1af8-4577-9949-93b00e33a223</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60f01b9e-7890-49cf-a0a1-161196cd44ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>deae3a07-6ca5-448b-9b7a-d0a4e54da36f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/User ingin melakukan checkout produk tanpa mengisi credentials last name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61cd0c24-17a4-4892-988d-7f892ed93038</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c77bbb8-72f3-4551-b883-305b1e743e99</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>954e7b44-c80e-42b4-80d8-022851d292d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/User ingin melakukan checkout produk tanpa mengisi credentials postal code</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e824a91-5adc-428a-8219-4eba8816d158</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49de892d-8ad2-4a32-b644-7dbc743e7063</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3afe7321-6292-4633-a97d-22e904be1850</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/User ingin melakukan checkout produk</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>caa67bc1-2f37-4102-b7ec-b906b04e4c58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dae2bb4-f887-4f7e-9730-57b44e914fca</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
