<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS001-Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>52896997-3bd7-45f4-9361-d9a62894ded2</testSuiteGuid>
   <testCaseLink>
      <guid>d098ab2b-e6de-4fbc-ba31-2fa7c5d83281</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/User melakukan login dengan credential valid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1229a38d-e9da-4faf-9f8a-3a53874b65aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52392c4c-8d2e-4291-9963-fc05b2987abc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2746854-bb62-4280-85ac-d11de1721195</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/User melakukan login dengan password invalid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43f7e4ce-77a9-4b7b-915f-d2ed0d8f3513</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a06569fd-3ff8-4863-b1b3-4698f42f4ca6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/User melakukan login dengan username invalid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d53d014-094c-452b-ae0f-db03270a749a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7106772b-69a2-407c-bfd2-e172bbae758c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1995095b-321a-46b0-9746-537a471e082a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/User melakukan login tanpa mengisi credential</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>55a1b20b-715b-4344-80d5-f779b9bc1b22</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/User melakukan logout setelah login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d75e62b-31a0-4c27-9eb5-e77b18438f36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fff44e19-5819-465d-9ff6-df167ec6eba3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
